services:
  - type: web
    name: ibinovirp-site
    runtime: python
    plan: free
    repo: https://github.com/douglasherzog/ibinovirp-site
    branch: main
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASS
        sync: false
